# Main ESPHome configuration for Living Room Hub
esphome:
  name: "living-room-hub"
  friendly_name: "Living Room Hub"
  on_boot:
    priority: -100
    then:
      # Wait until time is synchronized
      - while:
          condition:
            not:
              time.has_time:
          then:
            - logger.log: time not yet set
            - delay: 2s
      # Set desired state for filter relay based on time
      - if:
          condition:
            lambda: |
              auto hour = id(homeassistant_time).now().hour;
              return (hour >= 4 && hour < 12) || (hour >= 14 && hour < 23);
          then:
            - globals.set:
                id: should_filter_on
                value: "true"
          else:
            - globals.set:
                id: should_filter_on
                value: "false"
      # Set desired state for grow LED relay based on time
      - if:
          condition:
            lambda: |
              auto hour = id(homeassistant_time).now().hour;
              return (hour >= 7 && hour < 9);
          then:
            - globals.set:
                id: should_grow_led_on
                value: "true"
          else:
            - globals.set:
                id: should_grow_led_on
                value: "false"
      # Set desired state for heater relay based on temperature
      - lambda: |-
          if (id(aquarium_water_temperature).state < 26.5) {
            id(should_heater_on) = true;
          } else if (id(aquarium_water_temperature).state > 27.5) {
            id(should_heater_on) = false;
          }
      # Only turn on relays if mains power is present and their desired state is true
      - if:
          condition:
            binary_sensor.is_on: mains_power
          then:
            - if:
                condition:
                  lambda: "return id(should_filter_on);"
                then:
                  - switch.turn_on: filter_relay
            - if:
                condition:
                  lambda: "return id(should_heater_on);"
                then:
                  - switch.turn_on: heater_relay
            - if:
                condition:
                  lambda: "return id(should_grow_led_on);"
                then:
                  - switch.turn_on: grow_led_relay
      # Always turn off relays if mains is not present
      - if:
          condition:
            binary_sensor.is_off: mains_power
          then:
            - switch.turn_off: filter_relay
            - switch.turn_off: heater_relay
            - switch.turn_off: grow_led_relay
          else: 
            - switch.turn_on: filter_relay
      - if: 
          condition:
            - lambda: return id(homeassistant_time).now().hour >= 9 && id(homeassistant_time).now().hour < 21;
          then:
            - logger.log: time check passed for pump
            - delay: 20s
            - fan.turn_off: air_pump
            - fan.turn_on: 
                id: air_pump
                speed: 40

globals:
  - id: have_to_restore_filter_power
    type: bool
    initial_value: "false"
    restore_value: False
    # Tracks if filter power needs restoration after power loss
  - id: should_filter_on
    type: bool
    initial_value: "false"
    restore_value: False
    # Desired state for filter relay
  - id: should_heater_on
    type: bool
    initial_value: "false"
    restore_value: False
    # Desired state for heater relay
  - id: should_grow_led_on
    type: bool
    initial_value: "false"
    restore_value: False
    # Desired state for grow LED relay

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret default_native_api_encryption_key

ota:
  platform: esphome
  password: !secret default_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aquarium-Thingy Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80

# Time synchronization and scheduled actions
# Multiple on_time triggers for different automation times
# Used for light, air pump, and filter relay
# All use Home Assistant time
#
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: homeassistant
    on_time:
      hours: 22
      minutes: 00
      then:
        - light.turn_off: aquarium_light
        - fan.turn_off: air_pump
  - platform: homeassistant
    on_time:
      hours: 23
      minutes: 00
      then:
        - switch.turn_off: filter_relay
  - platform: homeassistant
    on_time:
      hours: 4
      minutes: 00
      then:
        - globals.set:
            id: should_filter_on
            value: "true"
        - if:
            condition:
              binary_sensor.is_on: mains_power
            then:
              - switch.turn_on: filter_relay
  - platform: homeassistant
    on_time:
      hours: 12
      minutes: 00
      then:
        - globals.set:
            id: should_filter_on
            value: "false"
        - switch.turn_off: filter_relay
  - platform: homeassistant
    on_time:
      hours: 14
      minutes: 00
      then:
        - globals.set:
            id: should_filter_on
            value: "true"
        - if:
            condition:
              binary_sensor.is_on: mains_power
            then:
              - switch.turn_on: filter_relay
  - platform: homeassistant
    on_time:
      hours: 23
      minutes: 00
      then:
        - globals.set:
            id: should_filter_on
            value: "false"
        - switch.turn_off: filter_relay
  - platform: homeassistant
    on_time:
      hours: 7
      minutes: 0
      then:
        - globals.set:
            id: should_grow_led_on
            value: "true"
        - if:
            condition:
              binary_sensor.is_on: mains_power
            then:
              - switch.turn_on: grow_led_relay
  - platform: homeassistant
    on_time:
      hours: 9
      minutes: 0
      then:
        - globals.set:
            id: should_grow_led_on
            value: "false"
        - switch.turn_off: grow_led_relay
        - fan.turn_off: air_pump
        - delay: 2s
        - fan.turn_on:
            speed: 40
            id: air_pump

# Sun-based automation for aquarium light
sun:
  latitude: 23.344101°
  longitude: 85.309563°
  on_sunset:
    - elevation: 10°
      then:
        - light.turn_on:
            id: aquarium_light
            brightness: 70%

# Aquarium light definition
light:
  - platform: monochromatic
    name: "Aquarium Light"
    id: aquarium_light
    output: light_pwm

# OneWire bus for temperature sensor
one_wire:
  - platform: gpio
    pin: D7 # GPIO13 -> D7
    id: one_wire_bus

# Mains power detection and relay control
binary_sensor:
  - platform: gpio
    pin:
      number: D5 # GPIO14 -> D5
      mode:
        input: True
      inverted: False
    name: "Mains Power"
    id: mains_power
    device_class: power
    on_state:
      then:
        # If mains lost, turn off all relays
        - if:
            condition:
              binary_sensor.is_off: mains_power
            then:
              - switch.turn_off: filter_relay
              - switch.turn_off: heater_relay
              - switch.turn_off: grow_led_relay
        # If mains returns, restore relays if their desired state is on
        - if:
            condition:
              binary_sensor.is_on: mains_power
            then:
              - if:
                  condition:
                    lambda: "return id(should_filter_on);"
                  then:
                    - switch.turn_on: filter_relay
              - if:
                  condition:
                    lambda: "return id(should_heater_on);"
                  then:
                    - switch.turn_on: heater_relay
              - if:
                  condition:
                    lambda: "return id(should_grow_led_on);"
                  then:
                    - switch.turn_on: grow_led_relay

# Water temperature sensor and heater control
sensor:
  - platform: dallas_temp
    address: 0xa93c01f096fcce28
    id: aquarium_water_temperature
    name: "Aquarium Water Temperature"
    unit_of_measurement: "°C"
    on_value:
      then:
        # Turn off heater if temp > 27.5°C and heater is on
        - if:
            condition:
              lambda: "return (x>27.5) && (id(heater_relay).state);"
            then:
              - globals.set:
                  id: should_heater_on
                  value: "false"
              - switch.turn_off: heater_relay
        # Turn on heater if temp < 26.5°C, heater is off, and mains is on
        - if:
            condition:
              lambda: "return (x<26.5) && !id(heater_relay).state;"
            then:
              - globals.set:
                  id: should_heater_on
                  value: "true"
              - if:
                  condition:
                    binary_sensor.is_on: mains_power
                  then:
                    - switch.turn_on: heater_relay

# GPIO switches for filter, heater, and white LED relays
switch:
  - platform: gpio
    name: "Water Filter"
    id: "filter_relay"
    pin: D2 # GPIO4 -> D2
    inverted: True

  - platform: gpio
    name: "Water Heater"
    id: "heater_relay"
    pin: D1 # GPIO5 -> D1
    inverted: True

  - platform: gpio
    name: "Grow LED Bulb"
    id: "grow_led_relay"
    pin: D3 # GPIO0 -> D3
    inverted: False
    # Relay for white grow LED bulb to simulate sunlight for algae growth

# PWM outputs for air pump and light
output:
  - platform: esp8266_pwm
    pin: D6 # GPIO12 -> D6
    frequency: 1000 Hz
    max_power: 0.1
    id: air_pump_pwm

  - platform: esp8266_pwm
    id: light_pwm
    pin: D0 # GPIO16 -> D0 ; a bit tricky to use GPIO16 on ESP8266 but debts of the past i guess
    max_power: 0.85

# Air pump fan definition
fan:
  - platform: speed
    output: air_pump_pwm
    id: air_pump
    name: "Aquarium Air Pump"
    icon: mdi:chart-bubble
