esphome:
  name: wipro-smart-bulb
  friendly_name: Wipro Smart Bulb
  min_version: 2025.5.0
  name_add_mac_suffix: False
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: status_light
            brightness: 25%
            red: 0%
            green: 0%
            blue: 100%
            effect: pulse
    - priority: -600
      then:
        - delay: 1s
        - light.turn_on:
            id: status_light
            brightness: 25%
            red: 0%
            green: 100%
            blue: 0%
        - delay: 500ms
        - light.turn_off:
            id: status_light

preferences:
  flash_write_interval: 10min

esp8266:
  board: esp_wroom_02  # This supports 2MB flash
  framework:
    version: recommended
  restore_from_flash: True

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret default_native_api_encryption_key

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret default_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Wipro Bulb Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: white_brightness_output
    pin: GPIO5
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: color_temperature_output
    inverted: True
    pin: GPIO13
    frequency: 1000 Hz

light:
  - platform: rgbct
    id: main_light
    name: None
    red: red_output
    green: green_output
    blue: blue_output
    white_brightness: white_brightness_output
    color_temperature: color_temperature_output
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: True
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0.8s
    gamma_correct: 2.0
    effects:
      - random:
      - random:
          name: "Slow Random"
          transition_length: 15s
          update_interval: 30s
      - pulse: 
      - strobe    
      - flicker: 
          alpha: 90%
          intensity: 5%
  - platform: rgb
    id: status_light
    internal: true
    red: red_output
    green: green_output
    blue: blue_output


switch:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    entity_category: diagnostic

button:
  - platform: template
    name: "Reading Mode"
    icon: "mdi:book-open-page-variant"
    on_press:
      - light.turn_on:
          id: main_light
          brightness: 85%
          color_temperature: 4000 K
          transition_length: 1s
  
  - platform: template
    name: "Relaxation Mode"
    icon: "mdi:sofa"
    on_press:
      - light.turn_on:
          id: main_light
          brightness: 40%
          color_temperature: 2700 K
          transition_length: 1.5s
  
  - platform: template
    name: "Workspace Mode"
    icon: "mdi:desk"
    on_press:
      - light.turn_on:
          id: main_light
          brightness: 100%
          color_temperature: 5500 K
          transition_length: 1s

sensor:
  # Diagnostic Wi-Fi signal sensors
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
  - platform: copy
    name: "WiFi Signal Percent"
    unit_of_measurement: "%"
    source_id: wifi_signal_db
    filters:
      - lambda: |-
          return min(max(2 * (x + 100.0), 0.0), 100.0);
    entity_category: diagnostic
  
  # Add uptime sensor
  - platform: uptime
    name: "Bulb Uptime"
    update_interval: 900s
    entity_category: diagnostic
    filters:
      - lambda: return x / 3600.0;  # Convert to hours
    unit_of_measurement: "h"